# -*- coding: utf-8 -*-
"""RockPaperScissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uV5F_-lgdu01cfIYgRpvDjQOCxRP7b0Z
"""

# In this code, the user picks rock, paper, or scissors. The computer
# then chooses 0, 1, or 2 randomly. These correspond to rock, paper, and
# scissors. It then compares the user choice and the computer choice to see 
# who one. It repeats until there is a winner.

import random
def main():
    winner = False
    while(winner == False):
        #prompt user to choose R, P, or S
        userChoice = input("[R]ock, [P]aper, or [S]cissors")
        #will choose 0 as rock, 1 as paper, and 2 as scissors
        computerChoice = random.randint(0,2)
        
        if(userChoice == 'r' or userChoice == 'R'):
            if(computerChoice == 0):
                print("Both of you chose rock, no winner, try again")
            elif(computerChoice == 1):
                print("Computer chose paper, you chose rock, you lose")
                winner = True
            elif(computerChoice == 2):
                print("Computer chose scissors, you chose rock, you win")
                winner = True
        elif(userChoice == 's' or userChoice == 'S'):
            if(computerChoice == 0):
                print("Computer chose rock, you chose scissors, you lose")
                winner = True
            elif(computerChoice == 1):
                print("Computer chose paper, you chose scissors, you win")
                winner = True
            elif(computerChoice == 2):
                print("You both chose scissors, no winner, try again")          
        elif(userChoice == 'p' or userChoice == 'P'):
            if(computerChoice == 0):
                print("Computer chose rock, you chose paper, you win")
                winner = True
            elif(computerChoice == 1):
                print("You both chose paper, no winner, try again")
            elif(computerChoice == 2):
                print("Computer chose scissors, you chose paper, you lose")
                winner = True
        
        
        
    
    
main()