# -*- coding: utf-8 -*-
"""WE AUV Python Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12pklgk_KXkgAZiZggsigINh6Uma7dhqt

# WE AUV Python Practice

Rock Paper Scissors
"""

def RPS():
    import random as rand
    state = 1
    while state is 1: # keeps game running
        user_choice = input("Rock, Paper, Scissors! (R/P/S)") # R = Rock, P = Paper, S = Scissors
        com_choice = rand.choice(["Rock", "Paper", "Scissors"])
        if user_choice is 'R':
            if com_choice is "Rock":
                print("COM chose " + com_choice)
                print("Draw.")
            elif com_choice is "Paper":
                print("COM chose " + com_choice)
                print("You Lost!")
            else:
                print("COM chose " + com_choice)
                print("You Won!")
        elif user_choice is 'P':
            if com_choice is "Rock":
                print("COM chose " + com_choice)
                print("You Won!")
            elif com_choice is "Paper":
                print("COM chose " + com_choice)
                print("Draw.")
            else:
                print("COM chose " + com_choice)
                print("You Lost!")
        elif user_choice is 'S':
            if com_choice is "Rock":
                print("COM chose " + com_choice)
                print("You Lost!")
            elif com_choice is "Paper":
                print("COM chose " + com_choice)
                print("You Won!")
            else:
                print("COM chose " + com_choice)
                print("Draw.")
        else: # invalid input
            print("Please check your input.")
        replay = input("Play again? (Y): ") # other inputs will close the game
        if replay != 'Y':
            state = 0

RPS()